### ISSUE TITLE
Since synchronization.lib is only added to usage-requirements...

### ISSUE THREAD

**Issue by pdimov** [boostorg/atomic#51]
... but not to requirements, the CMake config file generated by b2 doesn't pick it up as a dependency. This probably means that everyone linking to Boost::atomic on Windows would need to link to synchronization.lib, although I haven't tried it.

**Comment by Lastique** [comment]
> everyone linking to Boost::atomic on Windows would need to link to synchronization.lib

Yes, this is outlined in the release notes. And also the library is linked via auto-link pragmas.

> Since synchronization.lib is only added to usage-requirements but not to requirements, the CMake config file generated by b2 doesn't pick it up as a dependency.

I'm not sure I understand why. I thought, CMake config was supposed to use `usage-requirements` primarily, to generate `PUBLIC` dependencies. `requirements` would only be used for `PRIVATE` dependencies. If so, it sounds like there is a bug in the CMake config generator.

**Comment by pdimov** [comment]
> If so, it sounds like there is a bug in the CMake config generator.

Maybe, but it's not so simple. First, CMake PUBLIC is merely a shortcut that sets both its equivalent of `requirements` and `usage-requirements` (`INTERFACE` is `usage-requirements` and `PRIVATE` is `requirements`.) So to generate `PUBLIC` we'd need to somehow extract the things that are in both b2's `requirements` and `usage-requirements`. But in this case it doesn't matter, because `IMPORTED` targets don't support `PUBLIC` or `PRIVATE`, just `INTERFACE`.

I no longer understand what `boost-install` does, if I ever did, but I suppose I just take `requirements` and put that into `INTERFACE_LINK_LIBRARIES` (there's no other place to put it.) This works for e.g. Filesystem which links to both `bcrypt` (which it has in its `requirements`) and `synchronization` (which it picks up from Atomic.)

It's still technically a bug, I suppose. It's odd for a library to link to something else just in its `usage-requirements` (that would be the b2 equivalent of a CMake compiled library having an `INTERFACE` dependency to another compiled library instead of `PUBLIC`) but it's technically legitimate.

**Comment by Lastique** [comment]
> But in this case it doesn't matter, because `IMPORTED` targets don't support `PUBLIC` or `PRIVATE`, just `INTERFACE`.

This is fine for shared libraries, but not for static. For shared libs, you only need to link with the library and whatever other dependencies that are needed just by its public headers (i.e. `usage-requirements` in b2 terms, `INTERFACE` in CMake terms). You don't need to link with `PRIVATE` dependencies (`requirements` in b2) as the shared library is already linked with them. For static libs, you also need to link with `PRIVATE` dependencies.

If that's not possible to express in one target then we either need to create two sets of targets (for shared and static libs) or conditionally add dependencies based on `BUILD_SHARED_LIBS` or `BOOST_ALL_DYN_LINK` or something.

**Comment by pdimov** [comment]
Yeah, I looked at the code, and (a) it was written by Steven Watanabe, and (b) it doesn't look at any requirements per se, it collects all the dependencies of a target. So the code looks at `boost_atomic`, collects its dependencies, of which there are none, and puts that into `LINK_INTERFACE_LIBRARIES`. Or rather, doesn't.

We do have two sets of targets. At the moment, only the static target gets any LINK_INTERFACE_LIBRARIES, the shared target gets nothing (i.e. I assume that all dependencies are private). So it won't work for a shared Atomic anyway even if `synchronization.lib` is put into `requirements`.

**Comment by Lastique** [comment]
So the problem is that the generator completely ignores `usage-requirements` then?

**Comment by pdimov** [comment]
Yes. As I said, it collects the dependencies of the target. `usage-requirements` don't affect its dependencies. The `usage-requirements` of Atomic affect the dependencies of Filesystem, but not those of Atomic.

**Comment by Lastique** [comment]
Well, I don't see what I can do in Boost.Atomic about this. This needs to be reported to boost-install.
