### ISSUE TITLE
Boost Atomic 1.78 breaks macOS/iOS integration

### ISSUE THREAD

**Issue by jayMcBee** [boostorg/atomic#55]
This recent change in Atomic
 
'Added a ulock backend for waiting and notifying operations on Darwin systems since Mac OS 10.12, iOS 10.0, tvOS 10.0 or watchOS 3.0'

Pretty much breaks all projects using Boost libraries that in turn depend on Atomic.
In our scenario we're using Boost Log on iOS/iPadOS and can no further submit updates to the App Store due to this change;
The *ulock functions are considered private API, thus automated checks detect the methods (doesn't matter if they're referenced or defined as a duplicate by Atomic) and any apps using Atomic are rejected ('Invalid Binary')

**Comment by Lastique** [comment]
Thank you for the report. I've added a new `BOOST_ATOMIC_NO_DARWIN_ULOCK` configuration macro that disables `ulock`-based implementation of waiting and notifying operations on Darwin systems. `ulock` will still be enabled by default, if supported by the target system.

**Comment by jayMcBee** [comment]
Wow, that was fast!
Thanks for the quick fix, I'll apply it immediately.

**Comment by jayMcBee** [comment]
Confirming that the new BOOST_ATOMIC_NO_DARWIN_ULOCK configuration macro works just fine to circumvent Apple's automated binary checks for private API usage.

**Comment by Lastique** [comment]
Thanks for the confirmation.
