### ISSUE TITLE
Documentation redirect link broken

### ISSUE THREAD

**Issue by glenfe** [boostorg/atomic#58]
Visiting https://www.boost.org/libs/atomic redirects to https://www.boost.org/doc/libs/1_79_0/doc/html/atomic.html which is 404:

> 404 Not Found
> File "/home/www/shared/archives/live/boost_1_79_0/doc/html/atomic.html" not found.
> Unable to find file.

The right link is: https://www.boost.org/doc/libs/1_79_0/libs/atomic/doc/html/index.html

The root index.html currently redirects to "../../doc/html/atomic.html" but should redirect to "doc/html/index.html" instead.

**Comment by Lastique** [comment]
Fixed, thanks. Could you update the docs on the website?

**Comment by glenfe** [comment]
Will do tonight.

**Comment by glenfe** [comment]
Fixed in 1.79 archives on live site.

**Comment by Lastique** [comment]
Thanks.
