### ISSUE TITLE
ldxp/stxp

### ISSUE THREAD

**Issue by cyring** [boostorg/atomic#67]
Hello,

https://github.com/boostorg/atomic/blob/08bd4e20338c503d2acfdddfdaa8f5e0bcf9006c/include/boost/atomic/detail/core_arch_ops_gcc_aarch64.hpp#L1730

If branch is taken where `stxp` is releasing `%[storage]` ?

**Comment by Lastique** [comment]
Nowhere. This is not a problem because the lock address will be either overridden by the next executed `ldxp` or cleared on the context switch.
